### ISSUE TITLE
Dependencies issues on Pop!_OS 22.04

### ISSUE THREAD

**Issue by fabriziofs** [boi4/dynwalls#8]
Maybe it's a good idea add to the list of requirements the '**feh**' package. I tried to execute `python3 dynwalls use /path/to/image.heic` and the output was:
```
File contains 4 images
Written to wallpaper-1.jpg
Written to wallpaper-2.jpg
Written to wallpaper-3.jpg
Written to wallpaper-4.jpg
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/path/to/dynwalls_clone/dynwalls/__main__.py", line 150, in <module>
    main()
  File "/path/to/dynwalls_clone/dynwalls/__main__.py", line 146, in main
    dw.act(arguments.action, arguments)
  File /path/to/dynwalls_clone/dynwalls/__main__.py", line 30, in act
    getattr(self, actionname)(args)
  File "/path/to/dynwalls_clonedynwalls/__main__.py", line 87, in use
    self.update()
  File "/path/to/dynwalls_clone/dynwalls/__main__.py", line 137, in update
    subprocess.run(args)
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'feh' 
```
Also, when i tried to execute `sudo apt install libheif` the output was:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libheif
```
To install the `heif-convert` I had to execute `sudo apt install libheif-examples` that had that package. Maybe this only happens on Pop!_OS but I think that specify the name of the package to download could help someone :)

**Comment by boi4** [comment]
Hello,
thanks for your interest in the project :)

The idea of `dynwalls setcmd` is that you specify the command line command that can be used in your setup to change the wallpaper.

For example, if you have some kind of Gnome version running, you would use
`dynwalls setcmd 'gsettings set org.gnome.desktop.background picture-uri {}'`

The `feh` command in the README is just an example that works for a lot of window managers (i3wm, ...). Because it depends on your setup I didn't write `feh` as a requirement there.

If I find time however, I could give a more extensive list of examples in the README for different setups.

About `libheif-convert`: Thanks for the info, I will update the README accordingly!

**Comment by boi4** [comment]
Just pushed a new commit 25ce410143194a5b4d55e27eae393f261d287914 that should explain the dependencies and setcmd better :) Gonna close this issue now.

**Comment by boi4** [comment]
Just pushed a new commit 25ce410143194a5b4d55e27eae393f261d287914 that should explain the dependencies and setcmd better :) Gonna close this issue now.

**Comment by fabriziofs** [comment]
Thank you very much for your time and the explanation!
